use blackjack;
SELECT  TABLE_NAME, COLUMN_NAME, ORDINAL_POSITION,
  DATA_TYPE, IS_NULLABLE
FROM    INFORMATION_SCHEMA.COLUMNS
WHERE   TABLE_SCHEMA = 'blackjack'
ORDER BY TABLE_NAME, ORDINAL_POSITION;


